# 00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to tensors

### Creating tensors

In [2]:
# SCALAR
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# VECTOR
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
matrix = torch.tensor([[7, 8], [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix[1]

tensor([ 9, 10])

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
# TENSOR
tensor = torch.tensor([[[1], [2]], [[3], [4]], [[5], [6]]])
tensor

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([3, 2, 1])

In [15]:
tensor[0]

tensor([[1],
        [2]])

### Random tensors

In [16]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8562, 0.8160, 0.5128, 0.7710],
        [0.3763, 0.2536, 0.0364, 0.3772],
        [0.7138, 0.1103, 0.5575, 0.7948]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(3, 244, 244) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

### Zeros and ones

In [19]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype, random_tensor.dtype # Default data type is torch.float32

(torch.float32, torch.float32)

### Creating a range of tensors and tensors-like

In [22]:
# Use torch.arange()
one_to_ten = torch.arange(1, 11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [24]:
# Float32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (e.g. float32)
                               device=None, # CPU/GPU/TPU
                               requires_grad=False) # Record the operations performed on the tensor
float_32_tensor.dtype

torch.float32

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [26]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [27]:
long_tensor = float_32_tensor.type(torch.LongTensor)
long_tensor.dtype

torch.int64

In [28]:
float_32_tensor * long_tensor

tensor([ 9., 36., 81.])

## Getting information about tensors

1. Tensors are not the right datatype - `tensor.dtype`
2. Tensors are not the right shapre - `tensor.shape`
3. Tensors are not on the same device - `tensor.device`

In [29]:
# Create a tensor
some_tensor = torch.rand([3, 4], device='cpu')
some_tensor

tensor([[0.7837, 0.2643, 0.9698, 0.8413],
        [0.3042, 0.4713, 0.8538, 0.5346],
        [0.4163, 0.8988, 0.8843, 0.8012]])

In [30]:
print(f"DataType: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

DataType: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


## Manipulating tensors

### Basic operations
Tensor operations include:
* Multiplication (element-wise)
* Matrix multiplication
* Division
* Addition
* Substraction


In [31]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [32]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [33]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [34]:
# Try out pytorch in-built functions
display(torch.mul(tensor, 10))
display(torch.add(tensor, 10))
display(torch.div(tensor, 10))

tensor([10, 20, 30])

tensor([11, 12, 13])

tensor([0.1000, 0.2000, 0.3000])

### Matrix multiplication

Two main ways to perfrom multiplications in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [35]:
#################
### Challenge ###
#################

# Perform a dot product of theese tensors (step by step)
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
display(t1)
t2 = torch.tensor([[7, 8], [9, 10], [11, 12]])
display(t2)

# Code
step1 = sum(t1[0] * torch.transpose(t2, 0, 1)[0]) # First row by first column
step2 = sum(t1[0] * torch.transpose(t2, 0, 1)[1]) # First row by second column
step3 = sum(t1[1] * torch.transpose(t2, 0, 1)[0]) # Second row by first column
step4 = sum(t1[1] * torch.transpose(t2, 0, 1)[1]) # Second row by second column

result = torch.tensor([[step1, step2], [step3, step4]])
result

tensor([[1, 2, 3],
        [4, 5, 6]])

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

tensor([[ 58,  64],
        [139, 154]])

In [36]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals:  {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


In [37]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [38]:
# Matrix multiplcation by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [39]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 411 µs, sys: 0 ns, total: 411 µs
Wall time: 419 µs


tensor(14)

In [40]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 91 µs, sys: 13 µs, total: 104 µs
Wall time: 108 µs


tensor(14)

## One of the most common errors in DL: Shape errors

There are two rules that matrix multiplications needs to satisfy:
1. The **inner dimensions** must match:
  * `(3, 2) @ (3, 2)` won't work
  * `(2, 3) @ (3, 2)` will work
  * `(3, 2) @ (2, 3)` will work
2. The resulting matrix shape will be the **outer dimensions**
  * `(2, 3) @ (3, 2)`  -> `(2, 2)`
  * `(3, 2) @ (2, 3)`  -> `(3, 3)`

In [41]:
#                          Outter dimensions
#                       v                    v
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))
#                          ^              ^
#                          Inner dimensions

tensor([[0.3980, 0.8590],
        [0.0753, 0.1745]])

To fix our tensor shape issues, we can manipulate the shape of one of the tensors using transpose.

A **transpose** switches the axis or dimensions of a given tensor

In [42]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

try:
  torch.mm(tensor_A, tensor_B)
except Exception as e:
  print(e)

mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


In [43]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [44]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- Inner dimensions must match")
torch.mm(tensor_A, tensor_B.T)

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- Inner dimensions must match


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc...

In [45]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [46]:
# Find the minimum value
x.min(), torch.min(x)

(tensor(1), tensor(1))

In [47]:
# Find the max
x.max(), torch.max(x)

(tensor(91), tensor(91))

In [48]:
# Find the average - note: the torch.mean() function  requires a tensor of float32 or complex datatype
x.type(torch.float32).mean(), torch.mean(x.type(torch.float32))

(tensor(46.), tensor(46.))

In [49]:
# Find the sum
x.sum(), torch.sum(x)

(tensor(460), tensor(460))

## Positional min/max

In [50]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [51]:
# Find the index position of the highest value
x.argmax(), torch.argmax(x)

(tensor(9), tensor(9))

In [52]:
# Find the index position of the lowest value

In [53]:
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - Reshapes an input tensor to a defined shape
* Viewing - Return a view of an input of a certain shape
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeezing - Removes all `1` dimensions from a tensor
* Unsqueezing - Add a `1` dimension to a tensor
* Permuting - Return a view of the input dimensions permuted (swapped) in a certain way

In [54]:
# Create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [55]:
# Add an extra dimension
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [56]:
# Change the view
z = x.view(3, 3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [57]:
# Note: Chaning z changes x (a view of a tensor shares the same memory as the original tensor)
z[:, 0][0] = 10
x, z

(tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]),
 tensor([[10.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]]))

In [58]:
# Revert changes
z[:, 0][0] = 1

In [59]:
# Stack tensors on top of each other
x_stacked_dim0 = torch.stack([x, x, x], dim=0)
x_stacked_dim1 = torch.stack([x, x, x], dim=1)
x_stacked_dim0, x_stacked_dim1

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.],
         [9., 9., 9.]]))

In [60]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape # Previous tensor

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [61]:
x_squeezed = x.squeeze()
x_squeezed, x_squeezed.shape # Squeezed tensor

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [62]:
# torch.unsqueeze() - adds a single dimension at a specific dimension
x_unsqueezed = x.unsqueeze(0)
x_unsqueezed, x_unsqueezed.shape # Tensor with an extra dimension at dimension 0

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [63]:
# torch.permute() - rearranges the dimensions of a tensor in a specific order
x_original = torch.rand(size=(224, 224, 3)) # [height, widht, color_channels]
x_original.shape

torch.Size([224, 224, 3])

In [64]:
# Permute the order so that the color dimension is the first one
x_permuted = x_original.permute(2, 0, 1)
x_permuted.shape # Note: torch.permute() returns a view!

torch.Size([3, 224, 224])

## Indexing (selecting data from tensors)

In [65]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [66]:
# Index on the first bracket
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [67]:
# Index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [68]:
# Index in the most inner bracket (last dimension, dim=2)
x[0][0][0]

tensor(1)

In [69]:
# Getting number 9
x[0][2][2]

tensor(9)

In [70]:
# You can also use ":" to select "all" from a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [71]:
# Get all values from 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [72]:
# Get all values of the 0th dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [73]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [74]:
# Challenge: Index on "x" to return 9
display(x[0, 2, 2])

# Challenge: Index on "x" to return 3, 6, 9
display(x[:, :, 2])

tensor(9)

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

* From data in NumPy to PyTorch tensor -> `torch.from_numpy(ndarray)`
* From data in PyTorch tensor to NumPy -> `torch.Tensor.numpy()`

In [75]:
# NumPy array to tensor

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [76]:
array.dtype

dtype('float64')

03:36:52