<a href="https://colab.research.google.com/github/daidan3k/LearningAI/blob/main/courses/Deep%20Learning%20PyTorch/00-pytorch-fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to tensors

### Creating tensors

In [2]:
# SCALAR
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# VECTOR
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
matrix = torch.tensor([[7, 8], [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix[1]

tensor([ 9, 10])

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
# TENSOR
tensor = torch.tensor([[[1], [2]], [[3], [4]], [[5], [6]]])
tensor

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([3, 2, 1])

In [15]:
tensor[0]

tensor([[1],
        [2]])

### Random tensors

In [16]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8106, 0.0728, 0.8498, 0.0141],
        [0.3974, 0.2349, 0.8410, 0.3881],
        [0.9468, 0.5628, 0.1640, 0.0489]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(3, 244, 244) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

### Zeros and ones

In [19]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype, random_tensor.dtype # Default data type is torch.float32

(torch.float32, torch.float32)

### Creating a range of tensors and tensors-like

In [22]:
# Use torch.arange()
one_to_ten = torch.arange(1, 11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [24]:
# Float32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (e.g. float32)
                               device=None, # CPU/GPU/TPU
                               requires_grad=False) # Record the operations performed on the tensor
float_32_tensor.dtype

torch.float32

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [26]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [27]:
long_tensor = float_32_tensor.type(torch.LongTensor)
long_tensor.dtype

torch.int64

In [28]:
float_32_tensor * long_tensor

tensor([ 9., 36., 81.])

## Getting information about tensors

1. Tensors are not the right datatype - `tensor.dtype`
2. Tensors are not the right shapre - `tensor.shape`
3. Tensors are not on the same device - `tensor.device`

In [29]:
# Create a tensor
some_tensor = torch.rand([3, 4], device='cpu')
some_tensor

tensor([[0.1330, 0.2830, 0.3025, 0.6413],
        [0.1149, 0.5835, 0.4417, 0.8124],
        [0.9199, 0.8969, 0.1384, 0.2271]])

In [30]:
print(f"DataType: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

DataType: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


## Manipulating tensors

### Basic operations
Tensor operations include:
* Multiplication (element-wise)
* Matrix multiplication
* Division
* Addition
* Substraction


In [31]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [32]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [33]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [34]:
# Try out pytorch in-built functions
display(torch.mul(tensor, 10))
display(torch.add(tensor, 10))
display(torch.div(tensor, 10))

tensor([10, 20, 30])

tensor([11, 12, 13])

tensor([0.1000, 0.2000, 0.3000])

### Matrix multiplication

Two main ways to perfrom multiplications in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [35]:
#################
### Challenge ###
#################

# Perform a dot product of theese tensors (step by step)
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
display(t1)
t2 = torch.tensor([[7, 8], [9, 10], [11, 12]])
display(t2)

# Code
step1 = sum(t1[0] * torch.transpose(t2, 0, 1)[0]) # First row by first column
step2 = sum(t1[0] * torch.transpose(t2, 0, 1)[1]) # First row by second column
step3 = sum(t1[1] * torch.transpose(t2, 0, 1)[0]) # Second row by first column
step4 = sum(t1[1] * torch.transpose(t2, 0, 1)[1]) # Second row by second column

result = torch.tensor([[step1, step2], [step3, step4]])
result

tensor([[1, 2, 3],
        [4, 5, 6]])

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

tensor([[ 58,  64],
        [139, 154]])

In [36]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals:  {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


In [37]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [38]:
# Matrix multiplcation by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [39]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 269 µs, sys: 35 µs, total: 304 µs
Wall time: 309 µs


tensor(14)

In [40]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 69 µs, sys: 9 µs, total: 78 µs
Wall time: 82.3 µs


tensor(14)

## One of the most common errors in DL: Shape errors

There are two rules that matrix multiplications needs to satisfy:
1. The **inner dimensions** must match:
  * `(3, 2) @ (3, 2)` won't work
  * `(2, 3) @ (3, 2)` will work
  * `(3, 2) @ (2, 3)` will work
2. The resulting matrix shape will be the **outer dimensions**
  * `(2, 3) @ (3, 2)`  -> `(2, 2)`
  * `(3, 2) @ (2, 3)`  -> `(3, 3)`

In [41]:
#                          Outter dimensions
#                       v                    v
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))
#                          ^              ^
#                          Inner dimensions

tensor([[0.4476, 0.5972],
        [0.4875, 0.5570]])

02:34:47