In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [3]:
digits = load_digits()

In [5]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [9]:
lr = LogisticRegression(max_iter=10000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9611111111111111

In [10]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9888888888888889

In [11]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9648148148148148

In [14]:
kf = KFold(n_splits=3, shuffle=True)

In [17]:
for train_index, text_indext in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, text_indext)

[0 4 5 6 7 8] [1 2 3]
[1 2 3 4 6 7] [0 5 8]
[0 1 2 3 5 8] [4 6 7]


In [18]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [22]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9888888888888889

In [24]:
folds = StratifiedKFold(n_splits=3, shuffle=True)

In [29]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(max_iter=10000), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

print("Logistic Regression scores:", np.mean(scores_lr))
print("SVM scores:", np.mean(scores_svm))
print("Random Forest scores:", np.mean(scores_rf))

Logistic Regression scores: 0.9599332220367279
SVM scores: 0.9860879243183084
Random Forest scores: 0.9749582637729549


In [33]:
print("Logistic Regression cross-validation score:", cross_val_score(LogisticRegression(max_iter=10000), digits.data, digits.target, cv=3).mean())
print("SVM cross-validation score:", cross_val_score(SVC(), digits.data, digits.target, cv=3).mean())
print("Random forest cross-validation score:", cross_val_score(RandomForestClassifier(), digits.data, digits.target, cv=3).mean())

Logistic Regression cross-validation score: 0.9298831385642737
SVM cross-validation score: 0.9699499165275459
Random forest cross-validation score: 0.9404563160823595
